# -------------------------------------------------------------------------------------
# Author Configuration
# -------------------------------------------------------------------------------------

name = "mxarcher"
email = "hi@mxarcher.com"
link = "https://github.com/mxarcher"
avatar = ""