# -------------------------------------------------------------------------------------
# Permalinks Configuration
# See: https://gohugo.io/content-management/urls/#permalinks
# -------------------------------------------------------------------------------------

# posts = ":year/:month/:filename"
posts = "/p/:slug/"
pages = "/:slug/"
private = ":sections[1:]/:filename"